# Generated by Django 5.1 on 2025-11-12 20:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_Antiguedades', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='piezaantiguedad',
            name='compradores',
        ),
        migrations.AddField(
            model_name='piezaantiguedad',
            name='comprador',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='piezas_compradas', to='app_Antiguedades.cliente', verbose_name='Comprador'),
        ),
        migrations.AddField(
            model_name='piezaantiguedad',
            name='fecha_venta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de venta'),
        ),
        migrations.AddField(
            model_name='piezaantiguedad',
            name='precio_venta',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Precio de venta'),
        ),
        migrations.DeleteModel(
            name='CompraPieza',
        ),
    ]
